swagger: '2.0'
info:
  title: Youtube Service API
  version: "0.1"
  description: API for basic youtube operations.
consumes:
  - application/json
produces:
  - application/json

paths:
  /UpdateChannelDetails:
    post:
      tags: [Tests]
      operationId: app.post_UpdateChannelDetails
      summary: Update youtube's channel info
      parameters:
        - name: UpdateChannelInfo
          in: body
          schema:
            $ref: '#/definitions/UpdateChannelInfo'
      responses:
        200:
          description: Updated Cchannel info
        404:
          description: Data validation error
  /Upload Video:
    post:
      tags: [Tests]
      operationId: app.PostInsertVideo
      summary: Upload new video
      parameters:
        - name: UploadVideo
          in: body
          schema:
            $ref: '#/definitions/UploadVideo'
          in: body
          schema:
            $ref: '#/definitions/UploadVideo'
      responses:
        200:
          description: Id of the uploaded video
          schema:
            $ref: '#/definitions/newVideoId'
  /Delete Video:
    delete:
      tags: [Tests]
      operationId: app.DeleteVideo
      summary: Delete video by id
      parameters:
        - name: VideoToDelete
          in: body
          schema:
            $ref: '#/definitions/VideoToDelete'
          in: body
          schema:
            $ref: '#/definitions/VideoToDelete'
      responses:
        200:
          description: Deleted video
          schema:
            type: object
            properties:
              pets:
                type: array
                items:
                  $ref: '#/definitions/VideoToDelete'
  /Upload Comment:
    delete:
      tags: [Tests]
      operationId: app.PostUploadComment
      summary: Upload comment to specific video
      parameters:
        - name: Comment
          in: body
          schema:
            $ref: '#/definitions/Comment'
          in: body
          schema:
            $ref: '#/definitions/Comment'
      responses:
        200:
          description: comment on video
          schema:
            type: object
            properties:
              pets:
                type: array
                items:
                  $ref: '#/definitions/Comment'
definitions:

  newVideoId:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        description: Channel's id
        example: "1bo10ebo12be0100"
        minLength: 1
        maxLength: 100

  UpdateChannelInfo:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        description: Channel's id
        example: "1bo10ebo12be0100"
        minLength: 1
        maxLength: 100
      title:
        type: string
        description: Channel's title
        example: "Test Automation Demo"
        minLength: 1
        maxLength: 100
      description:
        type: string
        description: Channel's description
        example: "My first channel"
        minLength: 1
        maxLength: 100
      bannerImage:
        type: string
        description: Channel's banner image
        example: "D:\\demoImage.png"
        minLength: 1
        maxLength: 100
  UploadVideo:
    type: object
    required:
      - fileName
      - description
      - title
    properties:
      fileName:
        type: string
        description: File Name
        example: "/ExampleTests/TestFileExample1.py"
        minLength: 1
        maxLength: 100
      description:
        type: string
        description: Description of the uploaded file
        example: "The best movie ever"
        minLength: 1
        maxLength: 100
      title:
        type: string
        description: Title for the uploaded video
        example: "Gil's movie"
        minLength: 1
        maxLength: 100
  VideoToDelete:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        description: video id
        example: "kb234j"
        minLength: 1
        maxLength: 100
